version: '3.8'

networks:
    app-network:
        driver: bridge

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: collabodb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    image: collabocraft-api
    container_name: collabocraft-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network  

volumes:
  postgres-data: