version: '3.8'

networks:
    app-network:
        driver: bridge

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: collabodb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    image: collabocraft-api
    container_name: collabocraft-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - minio
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network  

  minio:
    image: minio/minio
    container_name: minio_storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

volumes:
  postgres-data:
  minio_data:  